[package]
name = "mega_mailer"
version = "0.1.0"
authors = ["Ilya Volchenkov <ivolchenkov@megaputer.ru>"]
edition = "2021"

[dependencies]
axum = "=0.5.17"
cookie = "=0.16.1"
tower-cookies = "=0.8.0"
tower-http = { version = "=0.3.5", features = ["fs"] }
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.2"
serde = "1.0"
serde_json = "1.0"
serde_cbor = "0.11"
tokio = { version = "1.14.0", features = ["full"]}
tokio-util = "0.7.0"
tokio-stream = "0.1.8"
teloxide-core = { version = "=0.9.0", default-features = false, features = ["rustls"] }
teloxide = { version = "=0.12.0", default-features = false, features = ["rustls", "macros", "ctrlc_handler"] }
futures = "0.3"
redis = "0.22.1"
config = { version = "0.13.2", default-features = false, features = ["yaml"] }
rand = "0.8.4"
regex = "1.4"
lazy_static = "1.4"
cbc = "=0.1.2"
aes = "=0.8.2"
thiserror = "1.0"
imap = { version = "=2.4.1", default-features = false }
rustls-connector = { version = "=0.16.1" }
clokwerk = "0.3.5"
rustyknife = "0.2"
reqwest = { version = "=0.11.14", default-features = false, features = ["rustls-tls"] }
uuid = "1.1.2"
ctrlc = "3.1"
chrono = { version = "0.4", features = ["serde"] }
sentry = { version = "=0.29.1", default-features = false, features = ["backtrace", "contexts", "panic", "anyhow", "debug-images", "reqwest", "rustls", "tracing"] }
anyhow = "=1.0.68"
sentry-anyhow = "0.29.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[lib]
name = "common"
path = "src/lib/lib.rs"

[[bin]]
name = "web_server"
path = "src/web/main.rs"

[[bin]]
name = "mail_checker"
path = "src/mail_checker/main.rs"

[[bin]]
name = "telegram_bot"
path = "src/bot/main.rs"

[profile.release]
debug = true