[package]
name = "mega_mailer"
version = "0.1.0"
authors = ["Ilya Volchenkov <ivolchenkov@megaputer.ru>"]
edition = "2021"

[dependencies]
axum = "0.4.0"
cookie = "0.16.0"
tower-cookies = "0.5.1"
tower-http = { version = "0.2.3", features = ["fs"] }
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.2"
serde = "1.0"
serde_json = "1.0"
serde_cbor = "0.11"
tokio = { version = "1.14.0", features = ["full"]}
tokio-util = "0.7.0"
tokio-stream = "0.1.8"
teloxide = { version = "0.7.1", default-features = false, features = ["rustls", "macros", "ctrlc_handler", "dispatching2"] }
futures = "0.3"
redis = "0.21.4"
log = "0.4"
pretty_env_logger = "0.4"
config = { version = "0.12.0", default-features = false, features = ["yaml"] }
rand = "0.8.4"
regex = "1.4"
lazy_static = "1.4"
cbc = "0.1.1"
aes = "0.8.1"
thiserror = "1.0"
imap = { version = "=2.4.1", default-features = false }
rustls-connector = { version = "=0.15.0" }
clokwerk = "0.3.5"
rustyknife = "0.2"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
uuid = "0.8"
ctrlc = "3.1"
chrono = { version = "0.4", features = ["serde"] }
sentry = { git = "https://github.com/getsentry/sentry-rust", default-features = false, features = ["anyhow", "reqwest", "rustls", "backtrace", "contexts", "panic", "log", "tracing"] }

[patch.crates-io]
teloxide-core = { git = "https://github.com/teloxide/teloxide-core" }

[lib]
name = "common"
path = "src/lib/lib.rs"

[[bin]]
name = "web_server"
path = "src/web/main.rs"

[[bin]]
name = "mail_checker"
path = "src/mail_checker/main.rs"

[[bin]]
name = "telegram_bot"
path = "src/bot/main.rs"
