[package]
name = "mega_mailer"
version = "0.1.0"
authors = ["Ilya Volchenkov <ivolchenkov@megaputer.ru>"]
edition = "2018"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket" }
jwt = "0.13"
hmac = "0.10"
sha2 = "0.9"
serde = "1.0"
serde_json = "1.0"
serde_cbor = "0.11"
tokio = { version = "1.2", features = ["rt"]}
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot", default-features = false, features = ["rustls"] }
futures = "0.3"
redis = "0.20"
log = "0.4"
pretty_env_logger = "0.4"
config = { version = "0.10", default-features = false, features = ["yaml"] }
rand = "0.8"
regex = "1.4"
lazy_static = "1.4"
block-modes = "0.7"
aes = "0.6"
thiserror = "1.0"

[[bin]]
name = "mega_mailer"
path = "src/main.rs"
