[package]
name = "mega_mailer"
version = "0.1.0"
authors = ["Ilya Volchenkov <ivolchenkov@megaputer.ru>"]
edition = "2018"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket" }
jwt = "0.13"
hmac = "0.10"
sha2 = "0.9"
serde = "1.0"
serde_json = "1.0"
serde_cbor = "0.11"
tokio = { version = "1.2", features = ["rt"]}
teloxide = { git = "https://github.com/teloxide/teloxide", default-features = false, features = ["rustls", "macros"] }
futures = "0.3"
redis = "0.20"
log = "0.4"
pretty_env_logger = "0.4"
config = { version = "0.10", default-features = false, features = ["yaml"] }
rand = "0.8"
regex = "1.4"
lazy_static = "1.4"
block-modes = "0.7"
aes = "0.6"
thiserror = "1.0"
imap = { version = "=2.4.1", default-features = false }
rustls-connector = { version = "=0.13.1" }
schedule = { git = "https://gogs.ddosya.ml/ramb/shedule-rs.git" }
rustyknife = "0.2"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
uuid = "0.8"
ctrlc = "3.1"
chrono = { version = "0.4", features = ["serde"] }

[patch.crates-io]
teloxide-core = { git = "https://github.com/teloxide/teloxide-core" }

[lib]
name = "common"
path = "src/lib/lib.rs"

[[bin]]
name = "web_server"
path = "src/web/main.rs"

[[bin]]
name = "mail_checker"
path = "src/mail_checker/main.rs"

[[bin]]
name = "telegram_bot"
path = "src/bot/main.rs"
